
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'gadslh'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'name of your profile file'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
        gadslh:
                production: 
                        materialized: table
                staging:
                        materialized: ephemeral
        vars: 
                t_campaignStats: '`data-analytics-265916.google_ads.p_CampaignStats_1322269447`'
                t_campaign: '`data-analytics-265916.google_ads.p_Campaign_1322269447r`'
                t_ads: '`data-analytics-265916.google_ads.p_Ad_1322269447`'
                t_adStats: '`data-analytics-265916.google_ads.p_AdBasicStats_1322269447`'
                t_campaignConv: '`data-analytics-265916.google_ads.p_CampaignConversionStats_1322269447`'
                t_adGroupStats: '`data-analytics-265916.google_ads.p_AdGroupStats_1322269447`'
                t_adGroup: '`data-analytics-265916.google_ads.p_AdGroup_1322269447`'
                t_adGroupConv: '`data-analytics-265916.google_ads.p_AdGroup_1322269447`'
                convName1: '"name of first conversion"'
                convName2: '"name of second conversion"'
                convName3: '"name of third conversion"'
                
  
